sudo: required
dist: trusty
language: php

php:
  - 7.1
env:
  - FEDORA_VERSION="3.8.1"

before_install:
  - export ISLANDORA_DIR=$TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
before_script:
  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'
script:
  - $ISLANDORA_DIR/tests/scripts/travis_scripts.sh
  - $ISLANDORA_DIR/tests/scripts/run_tests.sh "Islandora"
